name: CI-CD Pipeline-YTELT

on:
    push:
        branches:

                - main
                - 'feature/*''


    pull_request:
        branches:
                - main

    workflow_dispatch:
    

    job: 

        build-and-push-image:

              runs-on: ubuntu-latest
              steps: 

                 - name: Checkout Code
                   uses: actions/checkout@v4

                 - name: Find Changed Files
                   id: changed-files-build
                   uses: tj-actions/changed-files@v45

                   with: 

                    files:  
                          dockerfile
                          requirements.txt

                 - name: Setup up docker buildx
                   if: steps.changed-files-build.outputs.any_changed == 'true'
                   uses: docker/setup-buildx-action@v3

                 - name: Login to dockerHub
                   if: steps.changed-files-build.outputs.any_changed == 'true'
                   uses: docker/login-action@v3
                   with:
                    username: ${{ vars.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}

                 - name: Build and push docker image
                   if: steps.changed-files-build.outputs.any_changed == 'true'
                   run: 
                      docker buildx build --push \
                        --tag ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest \
                        --tag ${{ vars.DOCKERHUB_NAMESPACE }}/${{ ars.DOCKERHUB_REPOSITORY }}:${{github.sha}} \
                        .

                    





              


                

